  services:
  - type: web
    name: penjualan
    env: php
    build:
      cacheDirectories:
        - vendor
    buildCommand: |
      composer install --prefer-dist --no-dev --optimize-autoloader
      php artisan route:cache
      php artisan view:cache
    startCommand: |
      sleep 10
      echo "DB_HOST: $DB_HOST"
      php artisan config:cache
      php artisan migrate --force
      php-fpm
    envVars: |
        - key: APP_ENV
          value: production
        - key: APP_KEY
          generateValue: true
        - key: DB_CONNECTION
          value: pgsql
        - key: DB_HOST
          fromDatabase:
            name: penjualan-db
            property: host
        - key: DB_PORT
          value: "5432"
        - key: DB_DATABASE
          fromDatabase:
            name: penjualan-db
            property: database
        - key: DB_USERNAME
          fromDatabase:
            name: penjualan-db
            property: user
        - key: DB_PASSWORD
          fromDatabase:
            name: penjualan-db
            property: password
